### PR TITLE
Add support for Python 3.10

### LINKED ISSUE #319: Add support for Python 3.10
### What is the expected enhancement?

Terra started to support Python 3.10 https://github.com/Qiskit/qiskit-terra/pull/7102
We need to check Python 3.10 in our CI.

Could you update Github actions to try Python 3.10, @manoelmarques?

### LINKED ISSUE #321: Update cplex extra requires
### What is the expected enhancement?

Currently setup.py has this

>'cplex': ["cplex; python_version < '3.9'"],

however a new version of cplex has been recently released that includes a version 3.9. Maybe with the 3.10 change this can be updated at the same time to < 3.10 and testing done with the 3.9 version

### PR DESCRIPTION
**Pull request by manoelmarques**
### Summary
Following Qiskit/qiskit-terra#7102
Fixes #319
Fixes #321

### Details and comments
There isn't cplex for python 3.10. Keeping the tutorials running under python 3.7 and 3.8

Even though docplex builds and installs on python 3.10, it is not advertised as working in neither python 3.9 nor python 3.10.
The tutorials under python 3.10 fail on docplex. I am keeping the tutorials CI running for python 3.7 and python 3.8 as before.

The failure occurs inside `08_cvar_optimization.ipynb`:
```
# create docplex model
mdl = Model("portfolio_optimization")
x = mdl.binary_var_list("x{}".format(i) for i in range(n))
objective = mdl.sum([mu[i] * x[i] for i in range(n)])
objective -= q * mdl.sum([sigma[i, j] * x[i] * x[j] for i in range(n) for j in range(n)])
mdl.maximize(objective)
mdl.add_constraint(mdl.sum(x[i] for i in range(n)) == budget)

# case to
qp = from_docplex_mp(mdl)
```
```
ImportError                               Traceback (most recent call last)
Input In [5], in <module>
      1 # create docplex model
      2 mdl = Model("portfolio_optimization")
----> 3 x = mdl.binary_var_list("x{}".format(i) for i in range(n))
      4 objective = mdl.sum([mu[i] * x[i] for i in range(n)])
      5 objective -= q * mdl.sum([sigma[i, j] * x[i] * x[j] for i in range(n) for j in range(n)])

File ~/opt/anaconda3/envs/Qiskitenv310/lib/python3.10/site-packages/docplex/mp/model.py:2349, in Model.binary_var_list(self, keys, lb, ub, name, key_format)
   2325 def binary_var_list(self, keys, lb=None, ub=None, name=str, key_format=None):
   2326     """ Creates a list of binary decision variables and stores them in the model.
   2327 
   2328     Args:
   (...)
   2347 
   2348     """
-> 2349     return self._var_list(keys, self.binary_vartype, name=name, lb=lb, ub=ub, key_format=key_format)

File ~/opt/anaconda3/envs/Qiskitenv310/lib/python3.10/site-packages/docplex/mp/model.py:2316, in Model._var_list(self, keys, vartype, lb, ub, name, key_format)
   2315 def _var_list(self, keys, vartype, lb=None, ub=None, name=str, key_format=None):
-> 2316     return self._lfactory.var_list(keys, vartype, lb, ub, name, key_format)

File ~/opt/anaconda3/envs/Qiskitenv310/lib/python3.10/site-packages/docplex/mp/mfactory.py:434, in ModelFactory.var_list(self, keys, vartype, lb, ub, name, key_format, create_container)
    432 if create_container:
    433     ctn = self._new_var_container(vartype, key_list=[fixed_keys], lb=lb, ub=ub, name=name)
--> 434     var_list = self.new_var_list(ctn, fixed_keys, vartype, lb, ub, actual_name, 1, key_format)
    435     ctn._attach_var_list(var_list)
    436 else:

File ~/opt/anaconda3/envs/Qiskitenv310/lib/python3.10/site-packages/docplex/mp/mfactory.py:470, in ModelFactory.new_var_list(self, var_container, key_seq, vartype, lb, ub, name, dimension, key_format, _safe_bounds, _safe_names, var_factory_fn, _add_container)
    468     xnames = name or []
    469 else:
--> 470     xnames = self._expand_names(key_seq, name, dimension, key_format)
    472 safe_lbs = _safe_bounds or not xlbs
    473 safe_ubs = _safe_bounds or not xubs

File ~/opt/anaconda3/envs/Qiskitenv310/lib/python3.10/site-packages/docplex/mp/mfactory.py:301, in ModelFactory._expand_names(self, keys, user_name, dimension, key_format)
    299 else:
    300     stringifier_ = self._get_stringifier(dimension, keys)
--> 301     actual_naming_fn = compile_naming_function(keys, user_name, dimension, key_format,
    302                                                stringifier=stringifier_)
    303     computed_names = [actual_naming_fn(key) for key in keys]
    304     return computed_names

File ~/opt/anaconda3/envs/Qiskitenv310/lib/python3.10/site-packages/docplex/mp/mfactory.py:125, in compile_naming_function(keys, user_name, dimension, key_format, _default_key_format, stringifier)
    121     else:
    122         # here keys are tuples of size >= 2
    123         return lambda key_tuple: fixed_format_string % key_tuple
--> 125 elif is_function(user_name):
    126     return user_name
    128 elif is_iterable(user_name):
    129     # check that the iterable has same len as keys,
    130     # otherwise thereis no more default naming and None cannot appear in CPLEX name arrays

File ~/opt/anaconda3/envs/Qiskitenv310/lib/python3.10/site-packages/docplex/mp/utils.py:220, in is_function(e)
    218     from collections.abc import Callable
    219 else:  # pragma: no cover
--> 220     from collections import Callable  # @UnresolvedImport
    221 return isinstance(e, Callable)

ImportError: cannot import name 'Callable' from 'collections' (/Users/manoel/opt/anaconda3/envs/Qiskitenv310/lib/python3.10/collections/__init__.py)
```

IMPORTANT:
Terra is backporting this. Once they release it to pypi, I will backport it as well. Do not backport before they release otherwise it will fail. The stable CI gets Terra from Pypi.

### CODE REVIEW

**Review by t-imamichi — DISMISSED** [review]

**Comment by t-imamichi** [comment]
Could you try #322? This should work with Python 3.10.

**Comment by manoelmarques** [comment]
I tested with python 3.10 and it works.

**Review by t-imamichi — APPROVED** [review]
Thanks!
